version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install flake8

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8
